apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: s3-example-bucket-elasticsearch
spec:
  clusterServiceClassExternalName: s3
  clusterServicePlanExternalName: production
  parameters:
    BucketName: dp-s3-elasticsearch
    EnableLogging: False
    EnableGlacierLifeCycle: False
    GlacierLifeCycleTransitionInDays: 0
    EnableVersioning: False
    BucketAccessControl: Private
    PreventDeletion: False
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: s3-custom-example-bucket-elasticsearch
spec:
  clusterServiceClassExternalName: s3-example
  clusterServicePlanExternalName: production
  parameters:
    BucketName: dp-s3-elasticsearch
    EnableLogging: False
    EnableGlacierLifeCycle: False
    GlacierLifeCycleTransitionInDays: 0
    EnableVersioning: False
    BucketAccessControl: Private
    PreventDeletion: False
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sqs-example
spec:
  clusterServiceClassExternalName: sqs
  clusterServicePlanExternalName: standard
  parameters:
    DelaySeconds: 5
    MaximumMessageSize: 262144
    MessageRetentionPeriod: 345600
    ReceiveMessageWaitTimeSeconds: 0
    UsedeadletterQueue: false
    VisibilityTimeout: 5
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sqs-example-fifo
spec:
  clusterServiceClassExternalName: sqs
  clusterServicePlanExternalName: fifo
  parameters:
    ContentBasedDeduplication: true
    DelaySeconds: 5
    MaximumMessageSize: 262144
    MessageRetentionPeriod: 345600
    ReceiveMessageWaitTimeSeconds: 0
    UsedeadletterQueue: false
    VisibilityTimeout: 5