apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: catalog
  namespace: aws
spec:
  chart:
    spec:
      chart: catalog
      sourceRef:
        kind: HelmRepository
        name: svc-cat
        namespace: aws
  interval: 1m
  install:
    remediation:
      retries: 3
---
