apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: svc-cat
  namespace: default
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/service-catalog
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-sb
  namespace: default
spec:
  interval: 1m
  url: https://awsservicebroker.s3.amazonaws.com/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-efs-csi-driver
  namespace: default
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver/